[package]
name = "blockkey"
version = "0.1.0"
authors = ["Miles Watson <contact@mileswatson.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = {version = "0.37.1", features = [ "tcp-tokio", "dns-tokio" ] }
futures = "0.3.15"
tokio = { version="1.6.0", features = [ "full", "rt" ] }
sha2 = "0.9.5"
data-encoding = "2.3.2"
im-rc = "15.0.0"